### ISSUE TITLE
Typo error on page /ch_ml/OvfAndUdf.html

### ISSUE THREAD

**Issue by trgiangdo** [phamdinhkhanh/deepai-book#7]
Trong trang này có 1 lỗi nhỏ lệch với chú thích tiếng Anh như ảnh đính kèm ạ.

![ảnh](https://user-images.githubusercontent.com/37588363/150664415-2bfdcf57-5836-4c2b-8c78-12f245e43bfa.png)

**Comment by NaincyKumariKnoldus** [comment]
Hey @trgiangdo I have fixed typo error on page /ch_ml/OvfAndUdf.html. Please Review my PR!

**Comment by phamdinhkhanh** [comment]
I already fixed this issue, thank you for your precious response.
![](https://imgur.com/zWl2X3u.png)
